application: tidy-nomad-842
version: 1
runtime: go
api_version: go1

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /.*
  script: _go_app
