runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css
  mime_type: text/css

- url: /js
  static_dir: js
  mime_type: application/javascript

- url: /lib/css
  static_dir: lib/css
  mime_type: text/css

- url: /lib/js
  static_dir: lib/js
  mime_type: application/javascript

- url: /lib/fonts
  static_dir: lib/fonts

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

- url: /slides
  static_dir: slides

- url: /.*
  script: auctora.application

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest

